---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/pages/content
  label: Pages
  create: documents
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - page
- type: document
  path: settings.json
  label: Site Settings
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: npm run build
  publish_command: gatsby build
  preview_output_directory: public
  output_directory: public
  instant_preview_command: yarn develop
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
